-- CHIFFREMENT

GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD= 'Passw0rd!abc'

GO

CREATE CERTIFICATE MonCert WITH SUBJECT = 'Chiffrement';
GO

CREATE SYMMETRIC KEY Cle WITH ALGORITHM = AES_256 ENCRYPTION BY CERTIFICATE MonCert;
GO

OPEN SYMMETRIC KEY Cle DECRYPTION BY CERTIFICATE MonCert;

declare @Value varbinary(max) = ENCRYPTBYKEY(KEY_GUID('Cle'), VENTE.Detail.PrixPaye);

CLOSE SYMMETRIC KEY Cle;

GO

